title: Jekyll:i채 k채ytt채v채 sivusto S2024
description: Tervetuloa sivustolle!
remote_theme: francescobianco/jekyll-html-pages@main

header_pages:
- index.md
- vko2.md

twitter_username: harjunmaa
github_username: Ismo-HH
